### ISSUE TITLE
Leaderboard in dark mode

### ISSUE THREAD

**Issue by apetl** [karangandhi272/findr#1]
When in dark mode you cannot see the leaderboard
![image](https://user-images.githubusercontent.com/65128980/171489095-f0ee33cd-1e2b-438e-9d7c-fae03f54fca8.png)
![image](https://user-images.githubusercontent.com/65128980/171489172-a52cd110-24df-448a-a44b-eb30d43576a3.png)

**Comment by karangandhi272** [comment]
fixed
